### ISSUE TITLE
Hash check failed. Key file seems corrupted.

### ISSUE THREAD

**Issue by doncasper** [baibaratsky/php-wmsigner#1]
Запустил php-wmsigner по примеру в описании и получил следующую ошибку:
**Hash check failed. Key file seems corrupted.**

Но файл ключей точно не поврежден, WebMoney Keeper WinPro принимает его без ошибок.

Может ли проблема заключаться в среде запуска?
Пример запускался на Win7 + OpenServer

**Comment by baibaratsky** [comment]
Попробуйте запустить версию `dev-master`, я добавил туда проверку на чтение из файла. Если выдаст ошибку `Error reading from the key file.`, скорее всего, проблема с правами доступа.
Если не выдаст, покажите свой код, предварительно удалив из него пароль и WMID.

**Comment by doncasper** [comment]
К сожалению ошибку выдает всё ту же: **Hash check failed. Key file seems corrupted.**

Привожу листинг кода файла **index.php**, как я и говорил, он полностью состоит из кода в примере:

``` php
<?php
  require_once(__DIR__ . '/vendor/autoload.php');

  use baibaratsky\WebMoney\Signer;

  $signer = new Signer('wmid', '/full/path/to/the/key.kwm', 'password');
  $data = 'Data to be signed';
  $signature = $signer->sign($data);
```

**Update 1:** Только что скомпилировал wmsigner на unix хостинге и протестировал ключь, подпись создает без проблем. Но там стоит Php 5.2, поэтому данный пример запустить нет возможности. Но с ключем проблем точно нету.

**Update 2:** Запустил на виртуальной машине под ubuntu, php 5.5.9, все та же ошибка выпадает, что **Hash check failed. Key file seems corrupted.**, так что проблема не в среде запуска.

**Update 3:** Спасибо за помощь, извините за беспокойство. Как оказалось ошибка не в программе, а в том что я скопировал рабочий файл ключей. Cделал в кипере резервную копию ключей с другим паролем и все заработало.

**Comment by andr2k** [comment]
Получаю такую же ошибку, к сожалению.  PHP 5.5.9 на Ubuntu.

**Comment by baibaratsky** [comment]
GMP есть или нет? Код покажете?

**Comment by andr2k** [comment]
Пардон, ошибся.
