### ISSUE TITLE
Hash check failed. Key file seems to be corrupted.

### ISSUE THREAD

**Issue by PhPPgAdminBug** [baibaratsky/php-wmsigner#15]
**Hash check failed. Key file seems to be corrupted.**

`use baibaratsky\WebMoney\WebMoney;
use Illuminate\Database\Eloquent\Model;
use baibaratsky\WebMoney\Api\X\X2\Request;
use baibaratsky\WebMoney\Request\Requester\CurlRequester;
use baibaratsky\WebMoney\Signer;
use baibaratsky\WebMoney\Api\X\X2;

class WebMoneyService extends Model
{
    private $service;

    public function __construct()
    {
    }

    public function payment()
    {
         $webMoney = new WebMoney(new CurlRequester);
        $request = new Request;
        $request->setSignerWmid('wmid');
        $request->setTransactionExternalId(1); // Unique ID of the transaction in your system
        $request->setPayerPurse('YOUR PURSE');
        $request->setPayeePurse('PAYEE PURSE');
        $request->setAmount(10.23); // Payment amount
        $request->setDescription('Test payment');
       $request->sign(new Signer('wmid', app_path() . '/certs/certificate.p12', 'pass'));

        return $request;

    }`

Using Laravel 5.4, Homestead on Vagrant, Ubuntu x64.

Tryied to reissue certeficate, no luck.

**Comment by baibaratsky** [comment]
`.p12` is not a key file. You should use light authentication.

**Comment by baibaratsky** [comment]
https://github.com/baibaratsky/php-webmoney#authentication-with-a-light-certificate

**Comment by PhPPgAdminBug** [comment]
Wow, so fast. I am trying 

`
use baibaratsky\WebMoney\Webmoney;
use baibaratsky\WebMoney\Api\X\X9\Request;
use baibaratsky\WebMoney\Api\X\X9\Response;
use baibaratsky\WebMoney\Request\Requester\CurlRequester;

class WebMoneyService extends Model
{
    private $service;

    public function __construct()
    {
    }

    public function payment()
    {
        $webMoney = new WebMoney(new CurlRequester);

        $request = new Request(Request::AUTH_LIGHT);
        $request->setRequestedWmid('my_wmid');
        $request->lightAuth(app_path() . '/Services/certificate.p12', app_path() . '/certs/certificate.p12', 'test');

        if ($request->validate()) {
            /** @var Response $response */
            $response = $webMoney->request($request);

            // The response from WebMoney is here: $response->getRawData()

            if ($response->getReturnCode() === 0) {
                echo $response->getPurseByName('Z000000000000')->getAmount();
            } else {
                echo 'Error: ' . $response->getReturnDescription();
            }
        }
        return $request;`


Go this ERROR

`
Error while performing request (could not load PEM client certificate, OpenSSL error error:0906D06C:PEM routines:PEM_read_bio:no start line, (no key found, wrong pass phrase, or wrong file format?))`

**Comment by baibaratsky** [comment]
I’m not so familiar with the Light auth, but it looks like you need to convert p12 to pem and key.
https://serverfault.com/questions/9708/what-is-a-pem-file-and-how-does-it-differ-from-other-openssl-generated-key-file

**Comment by PhPPgAdminBug** [comment]
Wow, cool, so fast, but still errors, maybe because i am sleepy.

`
use baibaratsky\WebMoney\Webmoney;
use baibaratsky\WebMoney\Api\X\X9\Request;
use baibaratsky\WebMoney\Api\X\X9\Response;
use baibaratsky\WebMoney\Request\Requester\CurlRequester;


class WebMoneyService
{
    private $service;

    public function __construct()
    {
    }

    public function payment()
    {
        $webMoney = new WebMoney(new CurlRequester);

        $request = new Request(Request::AUTH_LIGHT);
        $request->setRequestedWmid('my_wmid');
        $request->lightAuth(app_path() . '/certs/certificate.p12', str_random(55), 'test');

        if ($request->validate()) {
            /** @var Response $response */
            $response = $webMoney->request($request);

            // The response from WebMoney is here: $response->getRawData()

            if ($response->getReturnCode() === 0) {
                echo $response->getPurseByName('Z000000000000')->getAmount();
            } else {
                echo 'Error: ' . $response->getReturnDescription();
            }
        }
        return $request;
`

Got this error
`Error while performing request (could not load PEM client certificate, OpenSSL error error:0906D06C:PEM routines:PEM_read_bio:no start line, (no key found, wrong pass phrase, or wrong file format?))`

**Comment by PhPPgAdminBug** [comment]
I'll try now

**Comment by PhPPgAdminBug** [comment]
Yahooo! Thank you very much, finally it works. I spent all day learingn docs, creating, verifying account. Thank you again, i should ask here earlier.

**Comment by PhPPgAdminBug** [comment]
Is this Ok?


`Error: Server Error step=13 wmid:my_wmid
Request {#558 ▼
  #requestedWmid: "my_wmid"
  #authType: "light"
  #requestNumber: "150654928289296"
  #signerWmid: null
  #lightCertificate: "/home/vagrant/Code/certs/wm_cert.crt.pem"
  #lightKey: "/home/vagrant/Code/certs/wm_cert.key.pem"
  #lightPassword: "test"
  #url: "https://w3s.wmtransfer.com/asp/XMLPursesCert.asp"
  #errors: []
  #signature: null
}`

**Comment by PhPPgAdminBug** [comment]
Ok, converted into 2 new files. I have now 

`Error: Server Error step=13 wmid:my_wmid
Request {#558 ▼
  #requestedWmid: "my_wmid"
  #authType: "light"
  #requestNumber: "150654997547050"
  #signerWmid: "my_wmid"
  #lightCertificate: "/home/vagrant/Code/certs/wm_cert.crt.pem"
  #lightKey: "/home/vagrant/Code/certs/wm_cert.key.pem"
  #lightPassword: "test"
  #url: "https://w3s.wmtransfer.com/asp/XMLPursesCert.asp"
  #errors: []
  #signature: null
}`

As i understand this is because there is no money amount, or using x9 interface is not allowed for me. 

**1 - I need to use this one X2, for payouts in web app, and as i understand, for accepting payments, i need use **Web Merchant Interface** not  XML-interfaces, am i right?** 

2 - also,  for X2 interface 
`$request->sign(new Signer('my_wmid', /home/vagrant/Code/certs/wm_cert.key.pem, 'test'));`
tryied file wm_cert.kwm. Also tried generate different ways .key file. Like 
`pkcs12 -in 529763127606.p12 -nocerts -nodes -out 529763127606.key`

`pkcs12 -in 529763127606.p12 -out 529763127606.key`
Did not help

Throws error i said before
`Hash check failed. Key file seems to be corrupted`

I am  really confused about docs and how it works. Stripe, PayPal was set up in couple hours first time.

Tried [https://wiki.webmoney.ru/projects/webmoney/wiki/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F_%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B9_WM_Keeper_WebPro_%D0%B2_PEM-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82](https://wiki.webmoney.ru/projects/webmoney/wiki/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F_%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B9_WM_Keeper_WebPro_%D0%B2_PEM-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82)

**Comment by PhPPgAdminBug** [comment]
For generated key from .p12 cert, with openssl on windows 10 i got .key file, and error

**Hash check failed. Key file seems to be corrupted.**

`$keyBuffer = self::readKeyBuffer($keyData, $wmid, $keyPassword);

        if ($keyBuffer === false) {
            // Try one more time using only the first half of the password
            $keyPassword = mb_substr(
                    $keyPassword,
                    0,
                    floor(mb_strlen($keyPassword, self::MB_ENCODING) / 2),
                    self::MB_ENCODING
            );
            $keyBuffer = self::readKeyBuffer($keyData, $wmid, $keyPassword);

            if ($keyBuffer === false) {
                throw new \Exception('Hash check failed. Key file seems to be corrupted.');
            }
        }`

for this code
`namespace App\Services;
use baibaratsky\WebMoney\WebMoney;
use baibaratsky\WebMoney\Signer;
use baibaratsky\WebMoney\Request\Requester\CurlRequester;
use baibaratsky\WebMoney\Api\X\X2;
class WebMoneyService
{
    private $service;
    public function __construct()
    {
    }
    public function payment()
    {
        $webMoney = new WebMoney(new CurlRequester);
        $request = new X2\Request;
        $request->setSignerWmid('my_wmid');
        $request->setTransactionExternalId(1); // Unique ID of the transaction in your system
        $request->setPayerPurse('my_z_purse');
        $request->setPayeePurse('my_z_purse');
        $request->setAmount(1000);
        $request->setDescription('Test payment');
        $request->sign(new Signer('my_wmid', app_path() . '/certs/wm_cert.key', 'test'));
        return $request;
`

**Comment by baibaratsky** [comment]
Once more, you shouldn’t use signer, you’ve got a Light certificate. If you see anything about signer, you are doing wrong.
Instead of `sign()` you have to go with the `lightAuth()` method.

**Comment by PhPPgAdminBug** [comment]
Yeah, i understand you now. Thank you very much for you time :)
