### ISSUE TITLE
What is "Data to be signed"

### ISSUE THREAD

**Issue by adibiut** [baibaratsky/php-wmsigner#16]
Hello. In the example there is a line which says:
$data = 'Data to be signed'; 

What is  'Data to be signed'? How should I make it?

**Comment by baibaratsky** [comment]
Hello!
It could be any string you want.
If you don’t know what you want to sign, I think you don’t need this package.
Probably [php-webmoney](https://github.com/baibaratsky/php-webmoney) is what you are looking for.
