### ISSUE TITLE
Передача ключа в виде строки

### ISSUE THREAD

**Issue by fedl** [baibaratsky/php-wmsigner#17]
If you have your key not in a file, it is possible to provide a key as a string:
$signer = new Signer('wmid', $yourKeyData, 'password');

Подскажите как правильно преобразовать key.kwm в строку для $yourKeyData ? Пытаюсь через base64 - ошибка  Key file not found

**Comment by fedl** [comment]
Вопрос снят. Ну конечно же прогоняем ключ через base64_encode, сохраняем ключ в проекте как строку и перед использованием декодируем обратно через base64_decode.

**Comment by baibaratsky** [comment]
@fedl, как вы уже поняли, base64_encode/decode здесь роли не играет. На вход подается просто содержимое файла ключа в строковом виде. Хранить вы его можете, как вам удобно, в том числе и закодированным в base64.

**Comment by fedl** [comment]
Андрей, здравствуйте,
Да, но ключ-то в файле находится в бинарном виде. Собственно поэтому 
возникло непонимание каким образом подать его в функцию в *строковом 
*виде, согласно документации. Изначально предположил что надо перевести 
его в строку через base64_encode и в таком виде подать в функцию, но это 
оказалось не верным.

Сейчас я предварительно преобразую ключ из бинарного вида в строку через 
base64_encode. Далее добавляю эту строку в файл с кодом, где она и 
"хранится". А перед подачей ключа в функцию делаю обратное 
преобразование строки через base64_decode. То есть получается что 
фактически на вход функции ключ передается не в виде строки а в 
*бинарном *виде.

Имеет место неточность в описании или я что-то неверно понимаю ?

С уважением, Федорук Александр.

20.07.2019 21:51, Andrei Baibaratsky пишет:

**Comment by baibaratsky** [comment]
> it is possible to provide a key as a string

Не вижу проблемы. Конструктор принимает тип данных string. Если строка не имеет человекочитабельный вид, она не перестает быть строкой. Посмотрите, например, какой тип данных возвращает упомянутая вами [base64_decode](https://www.php.net/manual/en/function.base64-decode.php).

**Comment by fedl** [comment]
>Посмотрите, например, какой тип данных возвращает упомянутая вами 
base64_decode <https://www.php.net/manual/en/function.base64-decode.php>.
Из руководства: The returned data may be binary.

В моем случае она как раз binary и возвращает

Да, я понимаю, что строка в php это не то, что строка в Си и может 
хранить бинарные данные. Но видимо моё Си-прошлое бунтует против этого 
). Я бы всё таки для лучшего понимания разделял понятия "данные в виде 
строки" и "binary данные"

С уважением, Федорук Александр

22.07.2019 13:55, Andrei Baibaratsky пишет:

**Comment by baibaratsky** [comment]
```
base64_decode ( string $data [, bool $strict = FALSE ] ) : string
```
Называйте их как хотите, но в php нет [типа данных](https://www.php.net/manual/en/language.types.intro.php) binary, здесь для этого используется string. Посмотрите, например, на [hex2bin](https://www.php.net/manual/en/function.hex2bin.php) или [pack](https://www.php.net/manual/en/function.pack.php).
