### ISSUE TITLE
Неудачная проверка kwm-файла

### ISSUE THREAD

**Issue by egorsmkv** [baibaratsky/php-wmsigner#6]
Сделал полное восстановление kwm-файла, но проверка суммы безуспешная.

В чем может быть проблема?

**Comment by egorsmkv** [comment]
Проблема оказалась аналогичной первой issue: #1 

```
Update 3: Спасибо за помощь, извините за беспокойство. Как оказалось ошибка не в
программе, а в том что я скопировал рабочий файл ключей. Cделал в кипере резервную 
копию ключей с другим паролем и все заработало.
```

**Comment by baibaratsky** [comment]
Хорошо. Я рад, что вы разобрались.

**Comment by egorsmkv** [comment]
Я переписываю класс Signer на Python.

Казалось бы, портировал все функции, вроде правильно, но вот незадача - ошибка. А оказываются она самая элементарная.

**Comment by egorsmkv** [comment]
Может быть, кому-то будет интересно - https://github.com/eg0r/wm-signer

**Comment by chuprik** [comment]
Егор, а почему вы не указали источник для вдохновения? :) Хороший тон, этика и т.д. :)

**Comment by egorsmkv** [comment]
@kotchuprik всё указано https://github.com/eg0r/wm-signer/blob/master/wm_signer/__init__.py 😄

**Comment by chuprik** [comment]
Хорошо хоть не в base64 спрятано :)

**Comment by egorsmkv** [comment]
Это распространенная практика писать информацию о пакете в **init**.py

**Comment by chuprik** [comment]
Я все же имел ввиду написать об этом в README.md, как это делают все на github :)

**Comment by egorsmkv** [comment]
Если Вы думаете, что я как-то занижаю авторство @baibaratsky, то это не так.

А как делают "все" мне совсем не интересно, главное, чтобы модулем знали как воспользоваться, для этого предназначен README.

_P.S. код https://github.com/baibaratsky/php-wmsigner основан на WMSigner'e из WMXI, но никаких сносок об этом я не видел._

**Comment by baibaratsky** [comment]
@eg0r, на самом деле нет. :)
Свой код я писал, изучая [официальные исходники WMSigner](http://github.com/eagleas/wmsigner) от WebMoney и их же [реализацию на Ruby](https://github.com/eagleas/webmoney/blob/master/lib/signer.rb).

**Comment by egorsmkv** [comment]
@baibaratsky извиняюсь за неправильное предположение.

Исходил из того, что данный код https://github.com/marliotto/wmxi/blob/master/WMSigner.php похож на Ваш.

**Comment by baibaratsky** [comment]
Похож в какой-то мере. И это неудивительно, ведь он написан на том же языке, реализует тот же алгоритм и имеет в основе все те же официальные исходники, либо производные от них. Мне он покзался слишком перегруженным из-за поддержки старых версий php. Кроме того, у меня был свой взгляд на некоторые алгоритмические решения. Поэтому я и захотел сделать свой велосипед.

**Comment by fxpp** [comment]
How can I get .kwm file. I have an account in http://processing.webmoney.ru/login.aspx?ReturnUrl=%2faccount.aspx. Can I able to get .kwm file and  how can I get this file or how can I generate this file?

**Comment by chuprik** [comment]
@fxpp https://www.google.com/search?q=kwm+webmoney&oq=kwm+webmoney&sourceid=chrome&ie=UTF-8
